#ifndef _WA_IPC_H_
#define _WA_IPC_H_

// Winamp IPC messages
#define WM_WA_IPC WM_USER

// IPC Commands
#define IPC_GETPLAYLISTDIR 214
#define IPC_REFRESHPLCACHE 247
#define IPC_PLAYFILE 100
#ifndef IPC_ENQUEUEFILE
#define IPC_ENQUEUEFILE 100
#endif
#ifndef IPC_PLAYFILEW
#define IPC_PLAYFILEW 1100
#endif
#ifndef IPC_ENQUEUEFILEW
#define IPC_ENQUEUEFILEW 1100
#endif
#define IPC_DELETE 101
#define IPC_STARTPLAY 102
#define IPC_ISPLAYING 104
#define IPC_GETOUTPUTTIME 105
#define IPC_SETPLAYLISTPOS 121
#define IPC_GETLISTLENGTH 124
#define IPC_GETPLAYLISTFILE 211
#define IPC_GETPLAYLISTTITLE 212

#endif
